### ISSUE TITLE
Probably non an issue

### ISSUE THREAD

**Issue by lucapaganotti** [jvelilla/mongo-eiffel-driver#2]
Hi, I would like to give a try to this on linux, I cloned the git repository and I think to have setup all the needed configurations. I'm able to compile the bson.ecf and the mongodb.ecf projects as eiffel libraries. I then created a simple test project that uses the two libraries but I get undefined references to some symbols when I try to even declare a **MONGODB_CLIENT** object. For example I get:

...
_C1/Cobj1.o: nella funzione "inline_F959_7110":
big_file_C1_c.c:(.text+0x141): riferimento non definito a "mongoc_client_set_appname"_
...

My externals are defined like this:

- an include that points to mongo-eiffel-driver/C/mongo-c-driver/include/libmongoc-1.0/ folder
- a linker flag containing
  - -_L/usr/lib/x86_64-linux-gnu_ --> the folder on my debian box where the mongodb and bson development libraries where installed
  - _-lmongoc-1.0_ -- > link with libmongoc-1.0
  - _-lbson-1.0_ --> link with libbson-1.0

Am I missing something?
Thank you for your work, this nice post and any answer you will send to me.

**Comment by jvelilla** [comment]
I guess you are using an older version, Try to install MongoDB using the following information
http://mongoc.org/libmongoc/current/installing.html#building-from-a-release-tarball

Let me know if helps.

**Comment by lucapaganotti** [comment]
Hi, thanks for your answer, I got the latest stable tarball of mongoc
library (v.1.12.0), Now I have to setup correctly my
mongo-c-driver-1.12.0/src/libbson/src/bson/*bson-config.h.in
<http://bson-config.h.in>*
and mongo-c-driver-1.12.0/src/libmongoc/src/mongoc/*mongoc-config.h.in
<http://mongoc-config.h.in>*, but it's seems a promising situation as all
the libbson undefined symbol errors have gone away after configuring
bson-config.h the right way.

Thank you, I'll let you know what happens once I'll finish with it.

----------------------------------------------------------------
-- Dott. Ing. Luca Paganotti
-- Via dei Giardini 9
-- 21035 Cunardo (VA)
-- 393 1346898
----------------------------------------------------------------
-- softech s.r.l. email:
-- luca.paganotti@softechweb.it
-- luca.paganotti@gmail.com
-- https://github.com/lucapaganotti
-- sourceforge email:
-- lucapaganotti@users.sourceforge.net
-- skype name: luca.paganotti
[image: http://it.linkedin.com/in/lucapaganotti]
<http://it.linkedin.com/in/lucapaganotti>
-- Mastodon: l <https://www.facebook.com/luca.paganotti.66>
ucapaganotti@fosstodon.org
-- ---------------------------------------------------------------
-- Mistakes are portals of discovery - JAAJ
--- --------------------------------------------------------------

**Comment by jvelilla** [comment]
That's good, the wrapper is under development so if you want to contribute 
please send pull request :)

Forgot to ask you: which version of Ubuntu are you using? and EiffelStudio?


/Javier

**Comment by lucapaganotti** [comment]
Hi, I'm using a debian box (debian_version = 9.5) and EiffelStudio 17.05.
for the time being I would like to experiment with mongodb and eiffel. I do
not exclude my future contribution to your project, so many thanks again!
----------------------------------------------------------------
-- Dott. Ing. Luca Paganotti
-- Via dei Giardini 9
-- 21035 Cunardo (VA)
-- 393 1346898
----------------------------------------------------------------
-- softech s.r.l. email:
-- luca.paganotti@softechweb.it
-- luca.paganotti@gmail.com
-- https://github.com/lucapaganotti
-- sourceforge email:
-- lucapaganotti@users.sourceforge.net
-- skype name: luca.paganotti
[image: http://it.linkedin.com/in/lucapaganotti]
<http://it.linkedin.com/in/lucapaganotti>
-- Mastodon: l <https://www.facebook.com/luca.paganotti.66>
ucapaganotti@fosstodon.org
-- ---------------------------------------------------------------
-- Mistakes are portals of discovery - JAAJ
--- --------------------------------------------------------------

**Comment by jvelilla** [comment]
Please let me know if you need some help on it.

**Comment by lucapaganotti** [comment]
Hi, you're very kind, if it will be the case I'll not miss the opportunity.
I'm currently trying to figure out how to write a c library wrapper using
eiffel. I'm trying to wrap libgeos_c C library as an exercise and finishing
the mongoc-config.h setup.

Thank you again.

----------------------------------------------------------------
-- Dott. Ing. Luca Paganotti
-- Via dei Giardini 9
-- 21035 Cunardo (VA)
-- 393 1346898
----------------------------------------------------------------
-- softech s.r.l. email:
-- luca.paganotti@softechweb.it
-- luca.paganotti@gmail.com
-- https://github.com/lucapaganotti
-- sourceforge email:
-- lucapaganotti@users.sourceforge.net
-- skype name: luca.paganotti
[image: http://it.linkedin.com/in/lucapaganotti]
<http://it.linkedin.com/in/lucapaganotti>
-- Mastodon: l <https://www.facebook.com/luca.paganotti.66>
ucapaganotti@fosstodon.org
-- ---------------------------------------------------------------
-- Mistakes are portals of discovery - JAAJ
--- --------------------------------------------------------------

**Comment by jvelilla** [comment]
@lucapaganotti just for info I will move the project soon to https://github.com/eiffelhub so them it's easier to fork it and submit patches.
Also, the master branch is not up to date, the new code is under the branch [med14092018](https://github.com/jvelilla/mongo-eiffel-driver/tree/med14092018)
